export const COURSE_REFERENCES = [
  "P. Raj, B. Sundaravadivazhagan, M. Ouaissa, V. Kavitha, and K. Shantha Kumari, Eds., Quantum Computing and Artificial Intelligence: The Industry Use Cases. Hoboken, NJ, USA: John Wiley & Sons / Scrivener Publishing LLC, 2025, ISBN: 978-1-394-24236-8.",
  "S. Ali, F. Chicano, and A. Moraglio, Eds., Quantum Computing and Artificial Intelligence: First International Workshop, QC+AI 2025, Philadelphia, PA, USA, March 3, 2025, Proceedings, ser. Communications in Computer and Information Science, vol. 2813. Cham, Switzerland: Springer Nature Switzerland AG, 2026, ISSN: 1865-0929 (print), 1865-0937 (electronic), ISBN: 978-3-032-15930-4 (print), 978-3-032-15931-1 (eBook). doi: 10.1007/978-3-032-15931-1.",
  "S. Ali, F. Chicano, and A. Moraglio, Eds., Quantum Computing and Artificial Intelligence: Second International Workshop, QC+AI 2026, Singapore, January 27, 2026, Proceedings, ser. Communications in Computer and Information Science, vol. 2872. Cham, Switzerland: Springer Nature Switzerland AG, 2026, ISSN: 1865-0929 (print), 1865-0937 (electronic), ISBN: 978-3-032-17624-0 (print), 978-3-032-17625-7 (eBook). doi: 10.1007/978-3-032-17625-7.",
  "Introduction to Hardware-Constrained Learning for Quantum Computing and Artificial Intelligence. Local authored curriculum source document used to extend the foundations portion of the course.",
  "Hardware-Constrained Learning for Quantum Computing and Artificial Intelligence Models. Local authored curriculum source document used to define the model-family and validation module.",
  "Intermediate Quantum Programming for Hardware-Constrained Learning for Quantum Computing and Artificial Intelligence. Local authored curriculum source document used to design the device-first programming module.",
  "Advanced Programming and Software Development for Hardware-Constrained Learning for Quantum Computing and Artificial Intelligence. Local authored curriculum source document used to shape the advanced software-engineering module.",
  "Quantum Finance Programming and Optimization for Hardware-Constrained Learning for Quantum Computing and Artificial Intelligence. Local authored curriculum source document used to extend the finance-focused specialization module.",
];
