import json
from pathlib import Path

from app.schemas import VideoChapter


CURATED_VIDEO_CHAPTERS: dict[str, list[VideoChapter]] = {
    "Quantum Computing and Artificial Intelligence 2025.mp4": [
        VideoChapter(
            id="2025-intro",
            title="Why Quantum plus AI",
            timestamp_start=0,
            timestamp_end=71,
            summary="Introduces the QC+AI field and frames it through the practical limitations of NISQ hardware.",
            transcript_excerpt="The opening frames QC+AI as a hardware-constrained field in which every quantum step must earn its place inside a practical hybrid workflow.",
        ),
        VideoChapter(
            id="2025-nisq",
            title="NISQ Bottlenecks",
            timestamp_start=71,
            timestamp_end=143,
            summary="Explains that current systems are constrained by noise, routing overhead, and limited qubit budgets.",
            transcript_excerpt="The video emphasizes that current hardware cannot absorb raw problem formulations without strong classical assistance.",
        ),
        VideoChapter(
            id="2025-routing",
            title="Compilation and Routing",
            timestamp_start=143,
            timestamp_end=287,
            summary="Focuses on code compilation, qubit routing, and the physical cost of mapping logical circuits to sparse hardware graphs.",
            transcript_excerpt="Compilation overhead is presented as a decisive engineering constraint rather than a software afterthought.",
        ),
        VideoChapter(
            id="2025-optimization",
            title="Hybrid Optimization Patterns",
            timestamp_start=287,
            timestamp_end=431,
            summary="Covers hybrid optimization loops and the role of classical search and learning around quantum subroutines.",
            transcript_excerpt="The recurring message is that classical intelligence often protects fragile quantum steps from infeasible search spaces.",
        ),
        VideoChapter(
            id="2025-applications",
            title="Applications and System Design",
            timestamp_start=431,
            timestamp_end=575,
            summary="Closes with application examples and a general argument for hybridization as the practical path in the NISQ era.",
            transcript_excerpt="The ending connects routing, noise mitigation, and application design into a coherent hybrid systems view.",
        ),
    ],
    "Quantum Computing and Artificial Intelligence 2026.mp4": [
        VideoChapter(
            id="2026-intro",
            title="Hybrid QC+AI Framing",
            timestamp_start=0,
            timestamp_end=71,
            summary="Opens with the broad framing of quantum computing and AI as mutually enabling disciplines under hardware constraints.",
            transcript_excerpt="The introduction positions quantum computing and AI as mutually enabling disciplines, then narrows quickly to what present hardware can sustain operationally.",
        ),
        VideoChapter(
            id="2026-feature-bottlenecks",
            title="Feature Bottlenecks and Representations",
            timestamp_start=71,
            timestamp_end=215,
            summary="Emphasizes that the quantum role in practical models often sits at a compact, expressive bottleneck.",
            transcript_excerpt="The video visually reinforces that representation density matters more than speculative end-to-end replacement.",
        ),
        VideoChapter(
            id="2026-systems",
            title="Systems and Physical Constraints",
            timestamp_start=215,
            timestamp_end=359,
            summary="Returns to hardware and systems limitations, including resource bottlenecks and the need for disciplined orchestration.",
            transcript_excerpt="It ties model design back to what the hardware can sustain physically and operationally.",
        ),
        VideoChapter(
            id="2026-applications",
            title="Hybrid Applications",
            timestamp_start=359,
            timestamp_end=503,
            summary="Surveys application stories in optimization and hybrid learning with an emphasis on workable interfaces between classical and quantum components.",
            transcript_excerpt="The strongest message is that useful workflows are hybrid by construction.",
        ),
        VideoChapter(
            id="2026-roadmap",
            title="Roadmap and Future Direction",
            timestamp_start=503,
            timestamp_end=575,
            summary="Ends on a roadmap of sustainable hybrid systems, including the resource and thermodynamic framing of quantum agents.",
            transcript_excerpt="The closing emphasizes future systems design, not merely isolated algorithmic novelty.",
        ),
    ],
    "Industry Use Cases.mp4": [
        VideoChapter(
            id="industry-intro",
            title="Industry 5.0 Framing",
            timestamp_start=0,
            timestamp_end=76,
            summary="Opens by framing QC+AI as an Industry 5.0 transition shaped by resilience, sustainability, and workload-specific deployment choices.",
            transcript_excerpt="The video positions industry adoption as a portfolio question rather than a single universal disruption claim.",
            transcript_status="curated_chapter_summary",
        ),
        VideoChapter(
            id="industry-finance-logistics",
            title="Finance and Logistics",
            timestamp_start=76,
            timestamp_end=196,
            summary="Covers optimization-heavy sectors such as finance, cryptoeconomics, route planning, inventory management, and traffic flow.",
            transcript_excerpt="The strongest emphasis is on anomaly detection, portfolio optimization, and real-time orchestration around quantum optimization steps.",
            transcript_status="curated_chapter_summary",
        ),
        VideoChapter(
            id="industry-healthcare-climate",
            title="Healthcare, Pharma, and Climate",
            timestamp_start=196,
            timestamp_end=330,
            summary="Explains why healthcare, pharmaceuticals, chemistry, and climate modeling are attractive when simulation and high-dimensional inference are central.",
            transcript_excerpt="This section distinguishes native molecular simulation stories from broader predictive-analytics claims.",
            transcript_status="curated_chapter_summary",
        ),
        VideoChapter(
            id="industry-networks-security",
            title="Networks and Cybersecurity",
            timestamp_start=330,
            timestamp_end=470,
            summary="Moves into telecommunications, quantum networking, post-quantum migration, blockchain, and the urgency of security transition planning.",
            transcript_excerpt="Cybersecurity is framed as a migration problem with present consequences, not merely a distant speculative use case.",
            transcript_status="curated_chapter_summary",
        ),
        VideoChapter(
            id="industry-consumer-commercial",
            title="Consumer and Commercial Outlook",
            timestamp_start=470,
            timestamp_end=604,
            summary="Closes with consumer technology, entrepreneurial opportunity, commercialization limits, and the readiness differences across sectors.",
            transcript_excerpt="The conclusion stresses that adoption depends on regulation, infrastructure maturity, and hybrid support systems around the quantum component.",
            transcript_status="curated_chapter_summary",
        ),
    ],
    "Module2_Routing, Graph Shrinking, and Logistics under Hardware Constraints.mp4": [
        VideoChapter(
            id="module2-logistics-framing",
            title="Logistics Complexity under NISQ Limits",
            timestamp_start=0,
            timestamp_end=92,
            summary="Frames supply-chain routing as an NP-hard optimization problem whose naive QUBO translation quickly exceeds near-term hardware budgets.",
            transcript_excerpt="The opening ties logistics value to combinatorial hardness, then makes clear that qubit scarcity and noise still dominate what can actually be executed.",
        ),
        VideoChapter(
            id="module2-graph-shrinking",
            title="Graph Shrinking before Quantum Execution",
            timestamp_start=92,
            timestamp_end=220,
            summary="Explains why learning-based graph shrinking is used to compress large logistics instances before they reach the quantum processor.",
            transcript_excerpt="Classical preprocessing is presented as mandatory because the quantum stage cannot absorb full-scale constrained logistics graphs directly.",
        ),
        VideoChapter(
            id="module2-mdp-gnn",
            title="MDP Formulation and GNN Policy Learning",
            timestamp_start=220,
            timestamp_end=344,
            summary="Covers the MDP state, action, and reward design that lets a GNN policy learn constraint-preserving merge decisions.",
            transcript_excerpt="The middle section emphasizes that feasibility must survive graph compression, which is why the policy network reasons over topology and constraint signals together.",
        ),
        VideoChapter(
            id="module2-rl-q-alm",
            title="RL-Q-ALM and Dynamic Penalty Control",
            timestamp_start=344,
            timestamp_end=468,
            summary="Shows how augmented Lagrangian logistics formulations are stabilized by reinforcement learning that tunes penalty schedules dynamically.",
            transcript_excerpt="The lecture treats SAC as a control layer that keeps constrained optimization feasible without collapsing the landscape into barren penalty regimes.",
        ),
        VideoChapter(
            id="module2-routing",
            title="Nested Routing and Post-Transpilation Depth Control",
            timestamp_start=468,
            timestamp_end=612,
            summary="Moves from optimization to compilation, focusing on nested Monte Carlo routing, SWAP inflation, and post-routing transpilation gains.",
            transcript_excerpt="Even after the optimization model is compressed, routing depth is still decisive because sparse connectivity can erase theoretical gains through extra gates.",
        ),
        VideoChapter(
            id="module2-infrastructure",
            title="Hybrid Infrastructure and Deployment Reality",
            timestamp_start=612,
            timestamp_end=732,
            summary="Closes with the colocation, thermal-management, and ecosystem requirements that make quantum logistics a full-stack systems problem.",
            transcript_excerpt="The ending broadens the lesson from algorithms to deployment, arguing that useful quantum logistics depends on classical compute, cooling, networking, and operational partnerships.",
        ),
    ],
    "Module3_Quantum Vision, GNN, and Few-Shot Hybrid Architectures.mp4": [
        VideoChapter(
            id="module3-vision-bottlenecks",
            title="QViTs and Attention Bottlenecks",
            timestamp_start=0,
            timestamp_end=104,
            summary="Opens by showing how quantum vision transformers target the quadratic attention burden of classical ViTs with a compact quantum bottleneck.",
            transcript_excerpt="The lecture starts from the claim that quantum value in perception is most plausible when it compresses a narrow, expensive interaction stage instead of replacing the full vision stack.",
        ),
        VideoChapter(
            id="module3-biomedical-vision",
            title="Biomedical Imaging and Parameter Efficiency",
            timestamp_start=104,
            timestamp_end=208,
            summary="Extends the vision discussion into biomedical imaging, emphasizing parameter-efficient hybrid models for data-scarce, high-resolution clinical settings.",
            transcript_excerpt="Biomedical examples are used to argue that parameter efficiency and bounded quantum placement matter more than generic superiority claims.",
        ),
        VideoChapter(
            id="module3-qgnn-jet-tagging",
            title="QGNNs, Jet Tagging, and Relational Encoding",
            timestamp_start=208,
            timestamp_end=322,
            summary="Moves into relational data, quantum graph encodings, and the QC-GCN jet-tagging case as an example of selective quantum message processing.",
            transcript_excerpt="The middle of the video treats graph structure as a natural fit for selective quantum encoding, but still keeps classical graph processing in the loop.",
        ),
        VideoChapter(
            id="module3-qgshap",
            title="Graph Explainability and QGShap",
            timestamp_start=322,
            timestamp_end=414,
            summary="Covers the explainability bottleneck in graph models and uses QGShap to connect quantum amplitude amplification to exact feature attribution.",
            transcript_excerpt="Interpretability is framed as a deployment gate, not a cosmetic add-on, especially for graph models used in regulated or high-stakes settings.",
        ),
        VideoChapter(
            id="module3-diffusion",
            title="Conditioned Quantum Diffusion for Few-Shot Learning",
            timestamp_start=414,
            timestamp_end=534,
            summary="Explains why conditioned quantum diffusion is taught as a low-data generative architecture with explicit label guidance and sampling constraints.",
            transcript_excerpt="Few-shot diffusion is presented as credible only when low-data gains are weighed against conditioning complexity and the cost of repeated hybrid sampling loops.",
        ),
        VideoChapter(
            id="module3-orchestration",
            title="QUBISS, Orchestration, and NISQ Deployment Reality",
            timestamp_start=534,
            timestamp_end=632,
            summary="Closes with quantum-assisted subset selection, orchestration bandwidth, decoherence, and the full-stack constraints that still bound deployable hybrid perception systems.",
            transcript_excerpt="The ending broadens Module 3 from individual model tricks to the infrastructure and co-design layers required to make hybrid vision and graph systems operationally believable.",
        ),
    ],
    "Module4_Expressive Bottlenecks Compression, Language, and Explanation.mp4": [
        VideoChapter(
            id="module4-bottleneck-framing",
            title="Expressive Bottlenecks as Structural Limits",
            timestamp_start=0,
            timestamp_end=106,
            summary="Opens by defining expressive bottlenecks as architectural limits in representation, aggregation, and dimensionality rather than as simple shortages of parameters.",
            transcript_excerpt="The lecture starts from the claim that scaling alone does not reliably repair structural failures in compression, language, or explanation pipelines.",
        ),
        VideoChapter(
            id="module4-graph-generative",
            title="Graph, Diffusion, and Spatial Constraints",
            timestamp_start=106,
            timestamp_end=220,
            summary="Explains how GNN over-smoothing, graph indistinguishability, and diffusion or spatial fidelity limits create distinct but related expressive bottlenecks.",
            transcript_excerpt="Graph reasoning and generative perception are grouped together as cases where classical architectures lose critical structure when aggregation or denoising assumptions become too restrictive.",
        ),
        VideoChapter(
            id="module4-language",
            title="Language Adaptation and Retrieval Bottlenecks",
            timestamp_start=220,
            timestamp_end=336,
            summary="Moves into transformer adaptation, retrieval, and semantic modeling limits that appear when language systems rely on brute-force scale instead of better representational structure.",
            transcript_excerpt="The language segment emphasizes that parameter count can mask localized bottlenecks in adaptation, normalization, and knowledge retrieval rather than eliminating them.",
        ),
        VideoChapter(
            id="module4-quantum-shift",
            title="Quantum Expressivity beyond Classical Geometry",
            timestamp_start=336,
            timestamp_end=446,
            summary="Introduces the quantum paradigm shift as a change in representational geometry, using Hilbert-space structure to justify denser hybrid bottlenecks.",
            transcript_excerpt="Quantum value is framed here as a representational shift that may reorganize what can be encoded efficiently, not as a free-standing promise of universal speedup.",
        ),
        VideoChapter(
            id="module4-compression-semantics",
            title="quINR and Quantum Contrastive Embeddings",
            timestamp_start=446,
            timestamp_end=566,
            summary="Covers quantum implicit neural compression and quantum contrastive word embeddings as two authored examples of compact hybrid representation design.",
            transcript_excerpt="The middle-late portion of the lesson ties compression and semantics together by showing how both tasks depend on careful encoding and on bridging classical objectives into physically meaningful quantum scores.",
        ),
        VideoChapter(
            id="module4-xai-energy",
            title="Quantum Explainability and the Energetic Horizon",
            timestamp_start=566,
            timestamp_end=681,
            summary="Closes with quantum-accelerated attribution and the broader argument that expressive bottlenecks are linked to the energy and hardware costs of classical scaling.",
            transcript_excerpt="The ending combines explanation with systems reality, arguing that better hybrid representations matter partly because classical preparedness and parameter growth now carry steep physical costs.",
        ),
    ],
    "Module6_From Algorithmic Novelty to Sustainable Hybrid Systems.mp4": [
        VideoChapter(
            id="module6-paradigm-shift",
            title="Paradigm Shift and Quantum Foundations",
            timestamp_start=0,
            timestamp_end=102,
            summary="Opens by reframing the field as a transition from classical-only computation toward hybrid architectures built around qubits, superposition, and sustainable system design.",
            transcript_excerpt="The lesson begins by arguing that the real shift is architectural: quantum computing matters when it changes how larger computational systems are organized rather than when it is treated as an isolated novelty.",
        ),
        VideoChapter(
            id="module6-vqa-frameworks",
            title="VQAs and Emerging Hybrid Frameworks",
            timestamp_start=102,
            timestamp_end=218,
            summary="Introduces variational quantum algorithms as the practical bridge between NISQ hardware and machine-learning workloads, then connects them to newer hybrid framework patterns.",
            transcript_excerpt="Variational loops are presented as the operational core of near-term QC+AI because they bind parameterized circuits to classical optimization instead of pretending current hardware can stand alone.",
        ),
        VideoChapter(
            id="module6-ai4qc",
            title="AI4QC, Graph Shrinking, and Routing Control",
            timestamp_start=218,
            timestamp_end=334,
            summary="Moves from QAI to AI4QC by covering hardware-software orchestration, learning-based graph shrinking, and qubit routing as resource-efficiency controls.",
            transcript_excerpt="This section treats preprocessing and routing not as support work but as the mechanisms that decide whether a quantum workload is physically executable and energetically defensible.",
        ),
        VideoChapter(
            id="module6-industry-infrastructure",
            title="Industry 5.0, Logistics, and Sustainable Infrastructure",
            timestamp_start=334,
            timestamp_end=462,
            summary="Connects the technical stack to Industry 5.0 through logistics resilience, renewable-grid management, and other sustainability-driven infrastructure problems.",
            transcript_excerpt="The infrastructure segment argues that hybrid systems matter when they improve resilience, efficiency, and human-centered deployment across real industrial networks.",
        ),
        VideoChapter(
            id="module6-healthcare",
            title="Healthcare and Life-Critical Hybrid Systems",
            timestamp_start=462,
            timestamp_end=570,
            summary="Covers clinical control, diagnostics, and risk classification as examples where narrowly bounded hybrid quantum models must be evaluated under high-stakes operational constraints.",
            transcript_excerpt="Healthcare is used here to show that hybrid value is only credible when the quantum role stays explicit, auditable, and tightly connected to the clinical decision path.",
        ),
        VideoChapter(
            id="module6-language-efficiency",
            title="Language Efficiency, QUBISS, and Explainability",
            timestamp_start=570,
            timestamp_end=660,
            summary="Shifts into language-model efficiency, subset selection, semantic compression, and explainability as parts of the broader resource-efficiency story.",
            transcript_excerpt="The late-middle section ties language efficiency to sustainability by showing how pruning, compact semantic representations, and targeted explainability mechanisms can reduce waste in large hybrid pipelines.",
        ),
        VideoChapter(
            id="module6-agents-crypto",
            title="Quantum Agents, Cryptographic Transition, and Outlook",
            timestamp_start=660,
            timestamp_end=738,
            summary="Closes with thermodynamic quantum agents, the post-quantum cryptographic imperative, and the final argument that future readiness is a systems, security, and energy problem.",
            transcript_excerpt="The ending widens the roadmap from model architecture to long-horizon transition planning, where agent efficiency and post-quantum security become part of the same strategic story.",
        ),
    ],
    "Introduction_to_Hardware-Constrained_Learning_for_Quantum_Computing_and_Artificial_Intelligence.mp4": [
        VideoChapter(
            id="hcl-intro-problem",
            title="Why Hardware-Constrained Learning",
            timestamp_start=0,
            timestamp_end=96,
            summary="Frames the course around the failure of simulator-first intuition on near-term quantum hardware.",
            transcript_excerpt="The opening argues that realistic QC+AI work starts from hardware limits, not from idealized circuit abstractions.",
        ),
        VideoChapter(
            id="hcl-intro-constraints",
            title="Physical Constraints That Shape Learning",
            timestamp_start=96,
            timestamp_end=240,
            summary="Covers noise, shallow depth, topology, shot budgets, and queueing as first-order learning constraints.",
            transcript_excerpt="Noise, limited coherence, and finite shots are treated as design inputs rather than downstream annoyances.",
        ),
        VideoChapter(
            id="hcl-intro-goldilocks",
            title="Trainability and the Goldilocks Regime",
            timestamp_start=240,
            timestamp_end=372,
            summary="Explains why near-term QC+AI models must balance expressivity against trainability under real-device limits.",
            transcript_excerpt="The middle section emphasizes that useful models live in a narrow region between underpowered shallow circuits and untrainable deep ones.",
        ),
        VideoChapter(
            id="hcl-intro-workflow",
            title="Hardware-First Design Workflow",
            timestamp_start=372,
            timestamp_end=522,
            summary="Builds a practical workflow for choosing model families from hardware budgets, baseline pressure, and validation needs.",
            transcript_excerpt="The presenter turns hardware realism into a concrete design checklist spanning budgets, baselines, and mitigation cost.",
        ),
        VideoChapter(
            id="hcl-intro-risks",
            title="Failure Modes and Acceptance Gates",
            timestamp_start=522,
            timestamp_end=684,
            summary="Closes with diagnostic patterns, benchmark discipline, and the conditions required for a believable QC+AI claim.",
            transcript_excerpt="The ending shifts from optimism to evidence, stressing diagnostics, baselines, and explicit acceptance criteria.",
        ),
    ],
    "The Hardware-First Imperative in Quantum Machine LearningHardware-Constrained_Learning_for_Quantum_Computing_and_Artificial_Intelligence_Models.mp4": [
        VideoChapter(
            id="hcl-models-landscape",
            title="Constraint Landscape Across Model Families",
            timestamp_start=0,
            timestamp_end=84,
            summary="Introduces VQCs, kernels, and continuous-variable models through the lens of hardware-bounded feasibility.",
            transcript_excerpt="The lecture opens by comparing model families only after imposing realistic device limits on depth, connectivity, and measurement cost.",
        ),
        VideoChapter(
            id="hcl-models-vqc",
            title="VQCs and Barren Plateaus",
            timestamp_start=84,
            timestamp_end=182,
            summary="Explains why expressive variational circuits can become effectively untrainable under noise and depth growth.",
            transcript_excerpt="Variational expressivity is treated as dangerous when it pushes gradients into noise-dominated barren regimes.",
        ),
        VideoChapter(
            id="hcl-models-kernels",
            title="Kernel Concentration and Reachability",
            timestamp_start=182,
            timestamp_end=282,
            summary="Covers the twin risks of kernel concentration and shallow-model reachability deficits.",
            transcript_excerpt="The talk warns that both overly rich and overly weak models can fail, just in different statistical ways.",
        ),
        VideoChapter(
            id="hcl-models-validation",
            title="Acceptance Criteria and Test Strategy",
            timestamp_start=282,
            timestamp_end=380,
            summary="Turns validation into a design-time concern with benchmark gates, ablations, and baseline discipline.",
            transcript_excerpt="Selection is framed as inseparable from the tests that would later justify claiming quantum utility.",
        ),
        VideoChapter(
            id="hcl-models-decision",
            title="Choosing a Defensible QC+AI Model",
            timestamp_start=380,
            timestamp_end=467,
            summary="Closes with decision heuristics for picking model families under trainability, cost, and evidence constraints.",
            transcript_excerpt="The conclusion argues that credible QC+AI modeling is mostly about rejecting unjustified complexity early.",
        ),
    ],
    "Intermediate_Quantum_Programming_for_Hardware-Constrained_Learning_for_Quantum_Computing_and_Artificial_Intelligence.mp4": [
        VideoChapter(
            id="hcl-programming-device-first",
            title="Device-First Programming Mindset",
            timestamp_start=0,
            timestamp_end=92,
            summary="Reorients programming around the execution realities of cloud quantum hardware rather than simulator convenience.",
            transcript_excerpt="The lecture starts by replacing simulator habits with an execution model dominated by queueing, calibration, and sampling cost.",
        ),
        VideoChapter(
            id="hcl-programming-gradients",
            title="Parameter-Shift and Gradient Estimation",
            timestamp_start=92,
            timestamp_end=206,
            summary="Explains why parameter-shift methods are more stable than naive finite differences on shot-noisy devices.",
            transcript_excerpt="Gradient estimation is presented as a hardware problem because sampling variance directly shapes training viability.",
        ),
        VideoChapter(
            id="hcl-programming-measurements",
            title="Shot Allocation and Measurement Grouping",
            timestamp_start=206,
            timestamp_end=318,
            summary="Shows how commuting-term grouping and adaptive shot allocation reduce runtime and variance.",
            transcript_excerpt="Execution cost falls only when measurement planning is treated as part of the model design, not as post-processing.",
        ),
        VideoChapter(
            id="hcl-programming-mitigation",
            title="Mitigation, Logging, and Debugging",
            timestamp_start=318,
            timestamp_end=456,
            summary="Connects error mitigation, diagnostics, and experiment logging to reproducible NISQ learning workflows.",
            transcript_excerpt="The middle-to-late sections focus on telling hardware failure apart from model failure through instrumentation.",
        ),
        VideoChapter(
            id="hcl-programming-benchmarking",
            title="Benchmarking Real Runtime Behavior",
            timestamp_start=456,
            timestamp_end=582,
            summary="Ends on benchmark discipline that includes transpilation, latency, shot use, and mitigation overhead.",
            transcript_excerpt="The closing broadens evaluation beyond accuracy so programming choices can be judged against their operational cost.",
        ),
    ],
    "Advanced_Programming_and_Software_Development_for_Hardware-Constrained_Learning_for_Quantum_Computing_and_Artificial_Intelligence.mp4": [
        VideoChapter(
            id="hcl-software-architecture",
            title="Quantum Hardware as a Software-System Boundary",
            timestamp_start=0,
            timestamp_end=96,
            summary="Frames advanced QC+AI as a software-architecture problem shaped by queueing, calibration drift, and orchestration cost.",
            transcript_excerpt="The lecture opens by treating the quantum processor as a fragile asynchronous co-processor that software must manage carefully.",
        ),
        VideoChapter(
            id="hcl-software-mlir",
            title="MLIR, Compilation, and Backend Abstraction",
            timestamp_start=96,
            timestamp_end=214,
            summary="Explains why compiler dialects, intermediate representations, and backend abstraction matter for portable QC+AI systems.",
            transcript_excerpt="Compilation is presented as a first-class design surface because it governs reuse, routing visibility, and vendor portability.",
        ),
        VideoChapter(
            id="hcl-software-caching",
            title="Caching and Differentiable Execution Pipelines",
            timestamp_start=214,
            timestamp_end=332,
            summary="Shows how caching, invalidation policy, and differentiable orchestration shape iterative hybrid workloads.",
            transcript_excerpt="Repeated variational execution makes cache strategy and dependency tracking part of the performance story, not an implementation afterthought.",
        ),
        VideoChapter(
            id="hcl-software-pulse",
            title="Pulse-Level Control and Runtime Optimization",
            timestamp_start=332,
            timestamp_end=468,
            summary="Connects pulse-level control to decoherence exposure, latency reduction, and native-hardware optimization.",
            transcript_excerpt="The middle-to-late sections argue that lower-level control can matter more than preserving a clean logical-gate abstraction.",
        ),
        VideoChapter(
            id="hcl-software-reliability",
            title="Reliability Engineering and Acceptance Gates",
            timestamp_start=468,
            timestamp_end=589,
            summary="Closes with reproducibility, seed management, energy accounting, and the reliability standards needed for deployable QC+AI software.",
            transcript_excerpt="The conclusion reframes advanced quantum software engineering as operational discipline around calibration, reproducibility, and measurable acceptance gates.",
        ),
    ],
    "Quantum_Finance_Programming_and_Optimization_for_Hardware-Constrained_Learning_for_Quantum_Computing_and_Artificial_Intelligence.mp4": [
        VideoChapter(
            id="hcl-finance-framing",
            title="Quantum Finance Under NISQ Limits",
            timestamp_start=0,
            timestamp_end=82,
            summary="Frames finance as a domain where hybrid optimization is more credible than broad quantum-speedup marketing.",
            transcript_excerpt="The opening emphasizes that finance adoption depends on hardware-aware workflows, not on abstract asymptotic claims.",
        ),
        VideoChapter(
            id="hcl-finance-workloads",
            title="Portfolio, Pricing, and Anomaly Targets",
            timestamp_start=82,
            timestamp_end=174,
            summary="Maps portfolio optimization, option pricing, anomaly detection, and credit tasks to realistic QC+AI methods.",
            transcript_excerpt="Different workloads are shown to favor different hybrid decompositions, encodings, and acceptance criteria.",
        ),
        VideoChapter(
            id="hcl-finance-implementation",
            title="Programming the Hybrid Finance Loop",
            timestamp_start=174,
            timestamp_end=266,
            summary="Explains how classical optimizers, QUBO formulations, and kernel or variational subroutines interact in practice.",
            transcript_excerpt="The implementation section repeatedly positions the quantum component as a bounded co-processor inside a larger financial stack.",
        ),
        VideoChapter(
            id="hcl-finance-risk",
            title="Model Risk and Benchmark Governance",
            timestamp_start=266,
            timestamp_end=360,
            summary="Covers baseline comparison, compilation overhead, explainability pressure, and model-risk controls.",
            transcript_excerpt="Operational finance demands stronger controls because a merely novel model is not enough to justify deployment cost.",
        ),
        VideoChapter(
            id="hcl-finance-acceptance",
            title="Acceptance Gates for Production Finance",
            timestamp_start=360,
            timestamp_end=450,
            summary="Closes with the acceptance thresholds needed before a QC+AI finance system should be treated as deployable.",
            transcript_excerpt="The final message is that financial usefulness depends on disciplined evidence, governance, and cost accounting.",
        ),
    ],
}


def _mark_curated_transcript_status(chapters: list[VideoChapter]) -> list[VideoChapter]:
    return [
        chapter
        if chapter.transcript_status != "chapter_summary_only"
        else chapter.model_copy(update={"transcript_status": "curated_chapter_summary"})
        for chapter in chapters
    ]


def load_video_chapters(transcripts_dir: Path, filename: str) -> list[VideoChapter]:
    transcript_file = transcripts_dir / f"{Path(filename).stem}.json"
    if transcript_file.exists():
        try:
            data = json.loads(transcript_file.read_text(encoding="utf-8"))
            return [VideoChapter.model_validate(item) for item in data.get("chapters", [])]
        except Exception:
            pass
    return _mark_curated_transcript_status(CURATED_VIDEO_CHAPTERS.get(filename, []))
